### ISSUE TITLE
More than one tab doesnt work properly

### ISSUE THREAD

**Issue by stevenhaymanbamboohr** [microsoft/azuredatastudio-mysql#228]
Type: <b>Bug</b>

1. Create New Query Tab: CONNECTIONS -> SERVERS -> (Right Click Existing Connection) -> New Query
2. Create Second New Query Tab: Command + N

Logs from renderer.log:
2023-11-14 08:36:09.886 [info] Creating new connection untitled:SQLQuery_3
2023-11-14 08:36:09.887 [info] Adding connection untitled:SQLQuery_3
2023-11-14 08:36:09.887 [info] Successfully added connection untitled:SQLQuery_3
2023-11-14 08:36:09.933 [info] GitHub Copilot extension is not installed, so contextualization is not needed.
2023-11-14 08:36:09.933 [info] GitHub Copilot contextualization is disabled, so contextualization is not needed.
2023-11-14 08:36:09.933 [info] Contextualization is not needed because the GitHub Copilot extension is not installed and/or contextualization is disabled.
2023-11-14 08:36:21.143 [error] h.defaultValue?.toLocaleLowerCase is not a function: TypeError: h.defaultValue?.toLocaleLowerCase is not a function
    at vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:219:9414
    at Array.forEach (<anonymous>)
    at m.getConnectionOptionsList (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:219:8919)
    at m.getNonDefaultOptionsString (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:219:9523)
    at ie.getNonDefaultOptions (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2403:76999)
    at i.getTitle (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1531:93688)
    at X.computeTabLabels (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3350:58668)
    at X.handleOpenedEditors (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3350:48344)
    at X.openEditor (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3350:48000)
    at ie.doShowEditor (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3453:17375)
    at ie.doOpenEditor (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3453:16781)
    at ie.openEditor (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3453:15477)
    at ne (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3350:53383)
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3350:53626)
    at _ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:443:35)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:214:51)
    at ZoneTask.invokeTask [as invoke] (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:525:38)
    at invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1727:22)
    at globalCallback (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1758:31)
    at HTMLDivElement.globalZoneAwareCallback (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1794:20)

Extension version: 1.0.0
Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:19:19.203Z)
OS version: Darwin arm64 23.0.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by two-bridges** [comment]
I'm seeing the same issue as @stevenhaymanbamboohr since installing the most recent MySQL extension update.  

For 8 of my 9 MySQL connections, I get this exception and the tab fails to operate.  

For those 8 problem connections, the tab label continues to report Disconnected, even though the database is connected and it appears to function.  
![image](https://github.com/microsoft/azuredatastudio-mysql/assets/1709902/f9caf2de-7adf-491b-923f-82784293d8d3)

Opening an additional tab only partially works.  Ie. the tab is not seen in the Exporer sidebar; and, the tab is not visible
![image](https://github.com/microsoft/azuredatastudio-mysql/assets/1709902/706a1f2a-87c4-4b39-a3a6-b7e21e8692ed)


When I try to change tab, I get this error popup (same as the console message from Developer Tools, I think)
![image](https://github.com/microsoft/azuredatastudio-mysql/assets/1709902/73ba6339-34ab-4131-91c2-78ad00940acd)

**Comment by two-bridges** [comment]
it seems the error comes from the defaultValue for `port` being a number...
![image](https://github.com/microsoft/azuredatastudio-mysql/assets/1709902/0349a811-627a-47ac-a268-04b760b3816c)

**Comment by two-bridges** [comment]
this is the same but for a working MySQL connection. 

The difference here is: 
* the working connection uses the default port 3306
* the broken connections all use an alternate port (eg 44444 for ssh tunnelling)

![image](https://github.com/microsoft/azuredatastudio-mysql/assets/1709902/7160dcbc-c267-4636-87e2-71d6476b1645)
